//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<int> Reciever { get; set; }
        public Nullable<System.TimeSpan> TimeSended { get; set; }
        public Nullable<int> Chat { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
