//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_chat
    {
        public int id { get; set; }
        public int user_id_ { get; set; }
        public int chat_id_ { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual Users Users { get; set; }
    }
}
